import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  ar: {
    title: "نموذج طلب خدمة إعداد خطة استراتيجية",
    description: "يرجى تعبئة النموذج التالي بالمعلومات المطلوبة لتقديم طلب إعداد خطة استراتيجية متكاملة لشركتكم. سيتم مراجعة الطلب والتواصل معكم في أقرب وقت.",
    steps: [
      {
        title: "بيانات الشركة",
        fields: {
          companyName: "الاسم التجاري للمؤسسة/الشركة",
          sector: "القطاع/النشاط الرئيسي",
          foundedYear: "سنة التأسيس",
          countryCity: "الدولة/المدينة",
          website: "الموقع الإلكتروني (إن وجد)",
          branchCount: "عدد الفروع",
          employeeCount: "عدد الموظفين الإجمالي",
          applicantName: "اسم مقدم الطلب",
          jobTitle: "المسمى الوظيفي",
          mobile: "رقم الجوال",
          email: "البريد الإلكتروني",
        },
        placeholders: {
          companyName: "أدخل الاسم التجاري",
          sector: "مثال: تقنية، صناعة، تجزئة...",
          foundedYear: "مثال: 2015",
          countryCity: "مثال: السعودية / الرياض",
          website: "www.example.com",
          branchCount: "عدد الفروع",
          employeeCount: "عدد الموظفين",
          applicantName: "أدخل اسمك الكريم",
          jobTitle: "المسمى الوظيفي",
          mobile: "01xxxxxxxxx",
          email: "example@email.com",
        },
      },
      {
        title: "سبب طلب الخطة الاستراتيجية",
        fields: {
          requestReasons: "اختر الهدف/الأهداف",
          otherRequestReason: "أخرى",
          challengeDescription: "وصف مختصر للتحدي أو الدافع",
        },
        placeholders: {
          otherRequestReason: "حدد السبب الآخر...",
          challengeDescription: "اكتب وصفاً مختصراً للتحدي أو الدافع الرئيسي...",
        },
        options: {
          requestReasons: [
            "تحديد اتجاه الشركة للأعوام القادمة",
            "إعادة صياغة/تحديث الرؤية والرسالة والقيم",
            "معالجة تراجع أداء أو نمو بطيء",
            "التوسع لأسواق/منتجات جديدة",
            "رفع الربحية وكفاءة الإنفاق",
            "توحيد الجهود بين الإدارات",
            "تجهيز الشركة لاستثمار/طرح/شراكات",
            "مواءمة الاستراتيجية مع الحوكمة",
          ],
        },
      },
      {
        title: "نبذة عن الوضع الحالي",
        fields: {
          challenge1: "التحدي الأول",
          challenge2: "التحدي الثاني",
          challenge3: "التحدي الثالث",
          challengesTitle: "أهم 3 تحديات استراتيجية تواجهونها الآن",
          strength1: "نقطة القوة الأولى",
          strength2: "نقطة القوة الثانية",
          strength3: "نقطة القوة الثالثة",
          strengthsTitle: "أهم 3 نقاط قوة تميزكم",
        },
        placeholders: {
          challenge1: "التحدي الاستراتيجي الأول...",
          challenge2: "التحدي الاستراتيجي الثاني...",
          challenge3: "التحدي الاستراتيجي الثالث...",
          strength1: "نقطة القوة الأولى...",
          strength2: "نقطة القوة الثانية...",
          strength3: "نقطة القوة الثالثة...",
        },
      },

      {
        title: "نطاق الخطة الاستراتيجية المطلوبة",
        fields: {
          scopeOptions: "اختر المطلوب",
          otherScopeOption: "أخرى",
        },
        placeholders: {
          otherScopeOption: "حدد النطاق الآخر...",
        },
        options: {
          scopeOptions: [
            "خطة استراتيجية شاملة 3–5 سنوات",
            "خطة متوسطة 1–3 سنوات",
            "استراتيجية قطاع/وحدة أعمال محددة",
            "استراتيجية توسع جغرافي",
            "استراتيجية نمو الإيرادات",
            "استراتيجية التحول التشغيلي/الرقمي",
            "استراتيجية الموارد البشرية والقدرات",
            "استراتيجية تجربة العميل",
          ],
        },
      },
      {
        title: "الأسواق والعملاء",
        fields: {
          currentClients: "العملاء المستهدفون حالياً",
          clientSegments: "أهم شرائح العملاء",
          currentRegions: "مناطق النشاط الحالية",
          targetMarkets: "أسواق/مناطق ترغبون دخولها",
          competitorsTitle: "أهم المنافسين الذين تعتبرونهم الأقرب لكم",
          competitor1: "المنافس الأول",
          competitor2: "المنافس الثاني",
          competitor3: "المنافس الثالث",
        },
        placeholders: {
          currentClients: "صف العملاء المستهدفين حالياً...",
          clientSegments: "أهم شرائح العملاء...",
          currentRegions: "مناطق النشاط الحالية...",
          targetMarkets: "الأسواق المستهدفة...",
          competitor1: "اسم المنافس الأول...",
          competitor2: "اسم المنافس الثاني...",
          competitor3: "اسم المنافس الثالث...",
        },
      },

      {
        title: "الأداء والمؤشرات الحالية",
        fields: {
          annualRevenue: "الإيرادات السنوية (آخر سنة)",
          growthRate: "نسبة النمو خلال آخر 2–3 سنوات",
          profitMargin: "صافي الربح أو هامش الربحية (إن أمكن)",
        },
        placeholders: {
          annualRevenue: "أدخل الإيرادات السنوية...",
          growthRate: "مثال: 15%",
          profitMargin: "مثال: 20%",
        },
      },

      {
        title: "المخرجات المتوقعة من وجهة نظر العميل",
        fields: {
          expectedOutputs: "اختر ما تتوقعون استلامه",
          otherExpectedOutput: "أخرى",
        },
        placeholders: {
          otherExpectedOutput: "حدد المخرجات الأخرى...",
        },
        options: {
          expectedOutputs: [
            "تشخيص الوضع الحالي (As-Is)",
            "تحليل السوق والمنافسين",
            "تحليل SWOT / PESTEL (حسب الحاجة)",
            "رؤية/رسالة/قيم محدثة",
            "محاور وأهداف استراتيجية واضحة",
            "مبادرات ومشروعات استراتيجية",
            "خارطة طريق تنفيذية",
            "KPIs ولوحات متابعة",
            "خطة إدارة تغيير واتصال داخلي",
          ],
        },
      },
      {
        title: "الإطار الزمني المتوقع",
        fields: {
          proposedStartDate: "تاريخ البدء المقترح",
          urgency: "مدى السرعة",
        },
        options: {
          urgency: [
            "عاجل (3–4 أسابيع)",
            "متوسط (1–2 شهر)",
            "شامل (2–3 أشهر)",
            "وفق خطة مقترحة من مشروعك",
          ],
        },
      },
      {
        title: "الملفات المرفقة",
        fields: {
          attachmentTypes: "يرجى إرفاق ما يلي إن توفر",
          files: "رفع الملفات",
        },
        options: {
          attachmentTypes: [
            "الهيكل التنظيمي",
            "قوائم مالية / ملخصات أداء",
            "خطط سابقة",
            "وصف المنتجات/الخدمات",
            "أي دراسات سوق سابقة",
          ],
        },
      },
    ],
    form: {
      next: "التالي",
      previous: "السابق",
      submit: "إرسال الطلب",
      submitting: "جاري الإرسال...",
      required: "مطلوب",
      optional: "اختياري",
      successTitle: "شكراً لك!",
      successMessage: "تم استلام طلبكم بنجاح. سيتم مراجعة البيانات والتواصل معكم في أقرب وقت ممكن.",
      errorSubmitting: "حدث خطأ أثناء إرسال الطلب. يرجى المحاولة مرة أخرى.",
      errorUnexpected: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
      errorUploading: "حدث خطأ أثناء رفع الملف. يرجى المحاولة مرة أخرى.",
      uploading: "جاري الرفع...",
      fileReady: "الملف جاهز للإرسال",
      uploadButtonText: "اضغط لرفع الملفات",
      uploadHelp: "يمكنك رفع ملفات PDF، صور، أو مستندات Word",
      stepOf: "من",
      addMore: "إضافة المزيد",
      other: "أخرى",
    },
    footer: {
      servicesTitle: "خدماتنا ومجالاتنا",
      branchesTitle: "الفروع",
      companyTitle: "شركة مشروعك",
      companyDescription: "نقدم حلول استشارية متكاملة لمساعدة الشركات على النمو والتطور في مختلف المجالات.",
      copyright: "جميع الحقوق محفوظة © شركة مشروعك 2025",
      services: [
        "الاستشارات الاقتصادية",
        "الاستشارات الإدارية",
        "الاستشارات التسويقية",
        "الاستشارات المالية",
        "خدمات التمويل",
      ],
      branches: [
        "الرياض",
        "دبي",
        "الدوحة",
        "مسقط",
        "بغداد",
        "القاهرة",
        "صنعاء",
      ],
    },
  },
  en: {
    title: "Strategic Plan Service Request Form",
    description: "Please fill out the following form with the required information to submit a request for preparing a comprehensive strategic plan for your company. Your request will be reviewed and we will contact you shortly.",
    steps: [
      {
        title: "Company Data",
        fields: {
          companyName: "Trade Name of the Organization/Company",
          sector: "Sector / Main Activity",
          foundedYear: "Year of Establishment",
          countryCity: "Country / City",
          website: "Website (if available)",
          branchCount: "Number of Branches",
          employeeCount: "Total Number of Employees",
          applicantName: "Applicant Name",
          jobTitle: "Job Title",
          mobile: "Mobile Number",
          email: "Email Address",
        },
        placeholders: {
          companyName: "Enter trade name",
          sector: "e.g., Technology, Manufacturing, Retail...",
          foundedYear: "e.g., 2015",
          countryCity: "e.g., Saudi Arabia / Riyadh",
          website: "www.example.com",
          branchCount: "Number of branches",
          employeeCount: "Number of employees",
          applicantName: "Enter your name",
          jobTitle: "Your job title",
          mobile: "01xxxxxxxxx",
          email: "example@email.com",
        },
      },
      {
        title: "Reason for Requesting the Strategic Plan",
        fields: {
          requestReasons: "Select Objective(s)",
          otherRequestReason: "Other",
          challengeDescription: "Brief Description of the Challenge or Driver",
        },
        placeholders: {
          otherRequestReason: "Specify other reason...",
          challengeDescription: "Write a brief description of the main challenge or driver...",
        },
        options: {
          requestReasons: [
            "Defining company direction for upcoming years",
            "Redefining/updating vision, mission, and values",
            "Addressing performance decline or slow growth",
            "Expanding to new markets/products",
            "Increasing profitability and spending efficiency",
            "Unifying departmental efforts",
            "Preparing company for investment/IPO/partnerships",
            "Aligning strategy with governance",
          ],
        },
      },
      {
        title: "Current Situation Overview",
        fields: {
          challenge1: "Challenge 1",
          challenge2: "Challenge 2",
          challenge3: "Challenge 3",
          challengesTitle: "Top 3 Strategic Challenges You Currently Face",
          strength1: "Strength 1",
          strength2: "Strength 2",
          strength3: "Strength 3",
          strengthsTitle: "Top 3 Strengths That Distinguish You",
        },
        placeholders: {
          challenge1: "First strategic challenge...",
          challenge2: "Second strategic challenge...",
          challenge3: "Third strategic challenge...",
          strength1: "First strength...",
          strength2: "Second strength...",
          strength3: "Third strength...",
        },
      },

      {
        title: "Scope of Required Strategic Plan",
        fields: {
          scopeOptions: "Select Required Scope",
          otherScopeOption: "Other",
        },
        placeholders: {
          otherScopeOption: "Specify other scope...",
        },
        options: {
          scopeOptions: [
            "Comprehensive strategic plan 3–5 years",
            "Medium-term plan 1–3 years",
            "Specific sector/business unit strategy",
            "Geographic expansion strategy",
            "Revenue growth strategy",
            "Operational/Digital transformation strategy",
            "HR and capabilities strategy",
            "Customer experience strategy",
          ],
        },
      },
      {
        title: "Markets & Clients",
        fields: {
          currentClients: "Currently Targeted Clients",
          clientSegments: "Main Client Segments",
          currentRegions: "Current Activity Regions",
          targetMarkets: "Markets/Regions You Wish to Enter",
          competitorsTitle: "Top Competitors You Consider Closest",
          competitor1: "Competitor 1",
          competitor2: "Competitor 2",
          competitor3: "Competitor 3",
        },
        placeholders: {
          currentClients: "Describe currently targeted clients...",
          clientSegments: "Main client segments...",
          currentRegions: "Current activity regions...",
          targetMarkets: "Target markets...",
          competitor1: "First competitor name...",
          competitor2: "Second competitor name...",
          competitor3: "Third competitor name...",
        },
      },

      {
        title: "Performance & Current Indicators",
        fields: {
          annualRevenue: "Annual Revenue (Latest Year)",
          growthRate: "Growth Rate Over Last 2–3 Years",
          profitMargin: "Net Profit or Profit Margin (if possible)",
        },
        placeholders: {
          annualRevenue: "Enter annual revenue...",
          growthRate: "e.g., 15%",
          profitMargin: "e.g., 20%",
        },
      },

      {
        title: "Expected Outputs (Client Perspective)",
        fields: {
          expectedOutputs: "Select What You Expect to Receive",
          otherExpectedOutput: "Other",
        },
        placeholders: {
          otherExpectedOutput: "Specify other outputs...",
        },
        options: {
          expectedOutputs: [
            "Current Situation Diagnosis (As-Is)",
            "Market & Competitor Analysis",
            "SWOT / PESTEL Analysis (as needed)",
            "Updated Vision/Mission/Values",
            "Clear Strategic Pillars & Objectives",
            "Strategic Initiatives & Projects",
            "Implementation Roadmap",
            "KPIs & Monitoring Dashboards",
            "Change Management & Internal Communication Plan",
          ],
        },
      },
      {
        title: "Expected Timeline",
        fields: {
          proposedStartDate: "Proposed Start Date",
          urgency: "Speed Level",
        },
        options: {
          urgency: [
            "Urgent (3–4 weeks)",
            "Medium (1–2 months)",
            "Comprehensive (2–3 months)",
            "Based on Mashroo3k's proposed plan",
          ],
        },
      },
      {
        title: "Attached Files",
        fields: {
          attachmentTypes: "Please Attach the Following if Available",
          files: "Upload Files",
        },
        options: {
          attachmentTypes: [
            "Organizational Structure",
            "Financial Statements / Performance Summaries",
            "Previous Plans",
            "Products/Services Description",
            "Any Previous Market Studies",
          ],
        },
      },
    ],
    form: {
      next: "Next",
      previous: "Previous",
      submit: "Submit Request",
      submitting: "Sending...",
      required: "Required",
      optional: "Optional",
      successTitle: "Thank You!",
      successMessage: "Your request has been received successfully. Your data will be reviewed and we will contact you as soon as possible.",
      errorSubmitting: "Error submitting request. Please try again.",
      errorUnexpected: "An unexpected error occurred. Please try again.",
      errorUploading: "Error uploading file. Please try again.",
      uploading: "Uploading...",
      fileReady: "File ready to submit",
      uploadButtonText: "Click to upload files",
      uploadHelp: "You can upload PDF, images, or Word documents",
      stepOf: "of",
      addMore: "Add More",
      other: "Other",
    },
    footer: {
      servicesTitle: "Our Services & Fields",
      branchesTitle: "Branches",
      companyTitle: "Mashroo3k Company",
      companyDescription: "We provide integrated consulting solutions to help companies grow and develop in various fields.",
      copyright: "All rights reserved © Mashroo3k Company 2025",
      services: [
        "Economic Consultations",
        "Administrative Consultations",
        "Marketing Consultations",
        "Financial Consultations",
        "Financing Services",
      ],
      branches: [
        "Riyadh",
        "Dubai",
        "Doha",
        "Muscat",
        "Baghdad",
        "Cairo",
        "Sana'a",
      ],
    },
  },
};